all: gdb_example1.o gdb_example2.o gdb_example3.o
	gcc -o gdb_example1 gdb_example1.o
	gcc -o gdb_example2 gdb_example2.o
	gcc -o gdb_example3 gdb_exmaple3.o
gdb_example1.o: gdb_example1.c
	gcc -c gdb_example1.c
gdb_example2.o: gdb_example2.c
	gcc -c gdb_example2.c
gdb_example3.o: gdb_example3.c
	gcc -c gdb_example3.c
